### ISSUE TITLE
cannot pickup css file

### ISSUE THREAD

**Issue by MM-cyi** [egorsmkv/simple-django-login-and-register#106]
Hi there. 

First off congrats for the amazing work you did. 

I am trying to edit the the style layout, via css file, but I am constantly failing. I tried all I could and I am starting to run out pf option. 
What css file should I edit to control the layout of the page, and where is that file located? 

Thanks! 
Marco

**Comment by egorsmkv** [comment]
Hello. 

Thanks.

What page are you editing?

**Comment by MM-cyi** [comment]
Thanks for your prompt reply. 

This is one folder is have been looking into: 
/content/assets/css
and this is the other one: 
/content/assets/vendor/bootstrap/css

I checked 

I ended up editing content/templates/layouts/defaul/page.html, and adding there my css definition
<style> 
css definition
</style>
Since that is inherited everywhere, it is consistently propagated 
By isnt there a general css file? I tried following href="{% static 'css/styles.css' %}" but that seems to have no effect...

And also, when I try to embed/incorporate bootstrap carousel, it is not working (properly). Some page layout is not as it should be. 
Any hint? 

Thanks 
M.

**Comment by egorsmkv** [comment]
Are you using with production mode or in debug?In debug it must work correctly. Also don’t forget to browse your project with disabled cache. Sent from my iPhoneOn 3 Feb 2023, at 19:33, Marco ***@***.***> wrote:﻿
Thanks for your prompt reply.
This is one folder is have been looking into:
/content/assets/css
and this is the other one:
/content/assets/vendor/bootstrap/css
I checked
I ended up editing content/templates/layouts/defaul/page.html, and adding there my css definition
<style> 
css definition
</style>
Since that is inherited everywhere, it is consistently propagated
By isnt there a general css file? I tried following href="{% static 'css/styles.css' %}" but that seems to have no effect...
And also, when I try to embed/incorporate bootstrap carousel, it is not working (properly). Some page layout is not as it should be.
Any hint?
Thanks
M.

**Comment by MM-cyi** [comment]
This solved my problem. Thank you very much for you kind help and for sharing this amazing project. 
"Also don’t forget to browse your project with disabled cache"
